### ISSUE TITLE
[OhMyZsh] History prefix search not working with OhMyZsh

### ISSUE THREAD

**Issue by nickbrinser** [withfig/autocomplete#651]
### Sanity checks

- [X] My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)
- [X] I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue
- [ ] I would like to work on this.

### What CLI tool does this relate to?

OhMyZsh

### Which statement makes the most sense?

There is a bug with this completion spec

### Describe the bug
when I type the start of a command e.g. npm then hit the up arrow, I simply see the previous command, even if it didn't start with npm

### Steps to reproduce
echo "hello"
pwd
type echo, hit up
It will say pwd

### Expected behavior
It will say echo "hello"

Zsh version
5.8

### Terminal emulator
Hyper.js

Additional context
I tried manually enabling omz plugin enable history-substring-search

**Comment by fwesss** [comment]
Fixed in 1.0.50

**Comment by nagman** [comment]
Is it?
I've installed the 1.0.52 and I still have this issue.
If I type the `zsh` command, it will fix this behavior and I can use the prefixed history plus the autocomplete of Fig.
But I have to run this command each time I open a new session or tab.
